// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

public partial class Clients
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [Column("surname")]
    [StringLength(255)]
    [Unicode(false)]
    public string Surname { get; set; } = null!;

    [Column("phone_number")]
    [StringLength(10)]
    [Unicode(false)]
    public string? PhoneNumber { get; set; }

    [Column("email")]
    [StringLength(320)]
    [Unicode(false)]
    public string Email { get; set; } = null!;

    [Column("address")]
    [StringLength(255)]
    [Unicode(false)]
    public string? Address { get; set; }

    [Column("password_hash")]
    [StringLength(255)]
    [Unicode(false)]
    public string? PasswordHash { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<Appointments> Appointments { get; set; } = new List<Appointments>();

    [InverseProperty("Client")]
    public virtual ICollection<Reviews> Reviews { get; set; } = new List<Reviews>();
}