// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

[Table("Employee_schedule")]
public partial class EmployeeSchedule
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("worker_id")]
    public int WorkerId { get; set; }

    [Column("day_of_the_week_id")]
    public int DayOfTheWeekId { get; set; }

    [Column("start_working_hour")]
    public TimeOnly? StartWorkingHour { get; set; }

    [Column("end_working_hour")]
    public TimeOnly? EndWorkingHour { get; set; }

    [ForeignKey("DayOfTheWeekId")]
    [InverseProperty("EmployeeSchedule")]
    public virtual DaysOfTheWeek DayOfTheWeek { get; set; } = null!;

    [ForeignKey("WorkerId")]
    [InverseProperty("EmployeeSchedule")]
    public virtual Employees Worker { get; set; } = null!;
}