// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

public partial class Items
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [Column("price")]
    public int Price { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<PurchaseOrders> PurchaseOrders { get; set; } = new List<PurchaseOrders>();

    [InverseProperty("Item")]
    public virtual ICollection<RemainingGoods> RemainingGoods { get; set; } = new List<RemainingGoods>();

    [InverseProperty("Item")]
    public virtual ICollection<ServiceItem> ServiceItem { get; set; } = new List<ServiceItem>();
}