// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

public partial class Payments
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("appointment_id")]
    public int AppointmentId { get; set; }

    [Column("sum")]
    public int Sum { get; set; }

    [Column("date", TypeName = "date")]
    public DateTime Date { get; set; }

    [ForeignKey("AppointmentId")]
    [InverseProperty("Payments")]
    public virtual Appointments Appointment { get; set; } = null!;
}