// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

[Table("Purchase_orders")]
public partial class PurchaseOrders
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("item_id")]
    public int ItemId { get; set; }

    [Column("amount")]
    public int Amount { get; set; }

    [Column("date")]
    public DateOnly Date { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("PurchaseOrders")]
    public virtual Items Item { get; set; } = null!;
}