// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

[Table("Remaining_goods")]
public partial class RemainingGoods
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("item_id")]
    public int ItemId { get; set; }

    [Column("number_of_items")]
    public int NumberOfItems { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("RemainingGoods")]
    public virtual Items Item { get; set; } = null!;
}