// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

public partial class Services
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [Column("duration")]
    public short Duration { get; set; }

    [Column("price")]
    public short Price { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<Appointments> Appointments { get; set; } = new List<Appointments>();

    [InverseProperty("Service")]
    public virtual ICollection<ServiceItem> ServiceItem { get; set; } = new List<ServiceItem>();
}