// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure;

public partial class ServiceItem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("service_id")]
    public int ServiceId { get; set; }

    [Column("item_id")]
    public int ItemId { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("ServiceItem")]
    public virtual Items Item { get; set; } = null!;

    [ForeignKey("ServiceId")]
    [InverseProperty("ServiceItem")]
    public virtual Services Service { get; set; } = null!;
}