// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace BeautySalon.Infrastructure.Database;

public partial class BeautySalonContext : DbContext
{
    public BeautySalonContext(DbContextOptions<BeautySalonContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appointments> Appointments { get; set; }

    public virtual DbSet<Clients> Clients { get; set; }

    public virtual DbSet<DaysOfTheWeek> DaysOfTheWeek { get; set; }

    public virtual DbSet<EmployeeSchedule> EmployeeSchedule { get; set; }

    public virtual DbSet<Employees> Employees { get; set; }

    public virtual DbSet<Expences> Expences { get; set; }

    public virtual DbSet<Items> Items { get; set; }

    public virtual DbSet<Payments> Payments { get; set; }

    public virtual DbSet<Positions> Positions { get; set; }

    public virtual DbSet<PurchaseOrders> PurchaseOrders { get; set; }

    public virtual DbSet<RemainingGoods> RemainingGoods { get; set; }

    public virtual DbSet<Reviews> Reviews { get; set; }

    public virtual DbSet<Salary> Salary { get; set; }

    public virtual DbSet<ServiceItem> ServiceItem { get; set; }

    public virtual DbSet<Services> Services { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(BeautySalonContext).Assembly);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
