// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeautySalon.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace BeautySalon.Infrastructure.Database;

public partial class BeautySalonContext : DbContext
{
    public BeautySalonContext(DbContextOptions<BeautySalonContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admins> Admins { get; set; }

    public virtual DbSet<Appointments> Appointments { get; set; }

    public virtual DbSet<Clients> Clients { get; set; }

    public virtual DbSet<DaysOfTheWeek> DaysOfTheWeek { get; set; }

    public virtual DbSet<EmployeeSchedule> EmployeeSchedule { get; set; }

    public virtual DbSet<Employees> Employees { get; set; }

    public virtual DbSet<Expences> Expences { get; set; }

    public virtual DbSet<Items> Items { get; set; }

    public virtual DbSet<Payments> Payments { get; set; }

    public virtual DbSet<Positions> Positions { get; set; }

    public virtual DbSet<PurchaseOrders> PurchaseOrders { get; set; }

    public virtual DbSet<RemainingGoods> RemainingGoods { get; set; }

    public virtual DbSet<Reviews> Reviews { get; set; }

    public virtual DbSet<Salary> Salary { get; set; }

    public virtual DbSet<ServiceItem> ServiceItem { get; set; }

    public virtual DbSet<Services> Services { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admins>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Appointments>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Appointm__3213E83F2C6FAC0A");

            entity.HasOne(d => d.Client).WithMany(p => p.Appointments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Appointme__clien__47DBAE45");

            entity.HasOne(d => d.Employee).WithMany(p => p.Appointments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Appointme__emplo__48CFD27E");

            entity.HasOne(d => d.Service).WithMany(p => p.Appointments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Appointme__servi__49C3F6B7");

            entity.HasOne(d => d.Status).WithMany(p => p.Appointments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Appointme__statu__4AB81AF0");
        });

        modelBuilder.Entity<Clients>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clients__3213E83FA59C96AE");
        });

        modelBuilder.Entity<DaysOfTheWeek>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Days_of___3213E83F4627725C");
        });

        modelBuilder.Entity<EmployeeSchedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3213E83F6E0395CB");

            entity.HasOne(d => d.DayOfTheWeek).WithMany(p => p.EmployeeSchedule)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Employee___day_o__412EB0B6");

            entity.HasOne(d => d.Worker).WithMany(p => p.EmployeeSchedule)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Employee___worke__403A8C7D");
        });

        modelBuilder.Entity<Employees>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3213E83F5854F278");

            entity.ToTable(tb => tb.HasTrigger("UpdateSalaryOnPercentageChange"));

            entity.HasOne(d => d.PositionNavigation).WithMany(p => p.Employees)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Employees__posit__3D5E1FD2");
        });

        modelBuilder.Entity<Expences>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Expences__3213E83F476EC1DC");
        });

        modelBuilder.Entity<Items>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Items__3213E83F41E41E9E");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Payments>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payments__3213E83F4F21E1DE");

            entity.HasOne(d => d.Appointment).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payments__appoin__4D94879B");
        });

        modelBuilder.Entity<Positions>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Position__3213E83F13F17919");
        });

        modelBuilder.Entity<PurchaseOrders>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Purchase__3213E83F23CDD3DF");

            entity.HasOne(d => d.Item).WithMany(p => p.PurchaseOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Purchase___item___5EBF139D");
        });

        modelBuilder.Entity<RemainingGoods>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Remainin__3213E83F4B508A1E");

            entity.HasOne(d => d.Item).WithMany(p => p.RemainingGoods)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Remaining__item___59063A47");
        });

        modelBuilder.Entity<Reviews>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Reviews__3213E83F699345AD");

            entity.HasOne(d => d.Client).WithMany(p => p.Reviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reviews__client___5070F446");
        });

        modelBuilder.Entity<Salary>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Salary__3213E83F145BD069");

            entity.HasOne(d => d.Employee).WithMany(p => p.Salary)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Salary__employee__5BE2A6F2");
        });

        modelBuilder.Entity<ServiceItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceI__3213E83FF952850A");

            entity.HasOne(d => d.Item).WithMany(p => p.ServiceItem)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ServiceIt__item___5629CD9C");

            entity.HasOne(d => d.Service).WithMany(p => p.ServiceItem)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ServiceIt__servi__5535A963");
        });

        modelBuilder.Entity<Services>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Services__3213E83FAF4A1D6A");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Status__3213E83F0A7217A4");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}