// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class AppointmentsConfiguration : IEntityTypeConfiguration<Appointments>
    {
        public void Configure(EntityTypeBuilder<Appointments> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Appointm__3213E83F2C6FAC0A");

            entity.HasOne(d => d.Client).WithMany(p => p.Appointments)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Appointme__clien__47DBAE45");

            entity.HasOne(d => d.Employee).WithMany(p => p.Appointments)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Appointme__emplo__48CFD27E");

            entity.HasOne(d => d.Service).WithMany(p => p.Appointments)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Appointme__servi__49C3F6B7");

            entity.HasOne(d => d.Status).WithMany(p => p.Appointments)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Appointme__statu__4AB81AF0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Appointments> entity);
    }
}
