// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class EmployeeScheduleConfiguration : IEntityTypeConfiguration<EmployeeSchedule>
    {
        public void Configure(EntityTypeBuilder<EmployeeSchedule> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3213E83F6E0395CB");

            entity.HasOne(d => d.DayOfTheWeek).WithMany(p => p.EmployeeSchedule)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Employee___day_o__412EB0B6");

            entity.HasOne(d => d.Worker).WithMany(p => p.EmployeeSchedule)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Employee___worke__403A8C7D");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeeSchedule> entity);
    }
}
