// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class EmployeesConfiguration : IEntityTypeConfiguration<Employees>
    {
        public void Configure(EntityTypeBuilder<Employees> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3213E83F5854F278");

            entity.ToTable(tb => tb.HasTrigger("UpdateSalaryOnPercentageChange"));

            entity.HasOne(d => d.PositionNavigation).WithMany(p => p.Employees)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Employees__posit__3D5E1FD2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employees> entity);
    }
}
