// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class ExpencesConfiguration : IEntityTypeConfiguration<Expences>
    {
        public void Configure(EntityTypeBuilder<Expences> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Expences__3213E83F476EC1DC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Expences> entity);
    }
}
