// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class PaymentsConfiguration : IEntityTypeConfiguration<Payments>
    {
        public void Configure(EntityTypeBuilder<Payments> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Payments__3213E83F4F21E1DE");

            entity.HasOne(d => d.Appointment).WithMany(p => p.Payments)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Payments__appoin__4D94879B");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Payments> entity);
    }
}
