// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class PurchaseOrdersConfiguration : IEntityTypeConfiguration<PurchaseOrders>
    {
        public void Configure(EntityTypeBuilder<PurchaseOrders> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Purchase__3213E83F23CDD3DF");

            entity.HasOne(d => d.Item).WithMany(p => p.PurchaseOrders)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Purchase___item___5EBF139D");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseOrders> entity);
    }
}
