// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class RemainingGoodsConfiguration : IEntityTypeConfiguration<RemainingGoods>
    {
        public void Configure(EntityTypeBuilder<RemainingGoods> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Remainin__3213E83F4B508A1E");

            entity.HasOne(d => d.Item).WithMany(p => p.RemainingGoods)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Remaining__item___59063A47");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RemainingGoods> entity);
    }
}
