// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class SalaryConfiguration : IEntityTypeConfiguration<Salary>
    {
        public void Configure(EntityTypeBuilder<Salary> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Salary__3213E83F145BD069");

            entity.HasOne(d => d.Employee).WithMany(p => p.Salary)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Salary__employee__5BE2A6F2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Salary> entity);
    }
}
