// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BeautySalon.Infrastructure;
using BeautySalon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace BeautySalon.Infrastructure.Database.Configurations
{
    public partial class ServiceItemConfiguration : IEntityTypeConfiguration<ServiceItem>
    {
        public void Configure(EntityTypeBuilder<ServiceItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceI__3213E83FF952850A");

            entity.HasOne(d => d.Item).WithMany(p => p.ServiceItem)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__ServiceIt__item___5629CD9C");

            entity.HasOne(d => d.Service).WithMany(p => p.ServiceItem)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__ServiceIt__servi__5535A963");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ServiceItem> entity);
    }
}
